language: php

php:
  - '7.3'
  - '7.4'
  - '8.0'

install: composer install --no-interaction --no-progress --prefer-dist --no-suggest --optimize-autoloader

script: vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: always
